default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: myqpp_development

test:
  <<: *default
  database: myqpp_test

production:
  <<: *default
  database: myqpp_production
